version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql-app

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3308:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root

  nginx:
    build: ../.docker/nginx
    restart: always
    ports:
      - "8889:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web