version: '3'

services:
  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: back_office
      MYSQL_ROOT_PASSWORD: root